package se.aigr20.botbot.opendota;

public enum MatchField {
  MATCH_ID("match_id"),
  ACCOUNT_ID("account_id"),
  PLAYER_SLOT("player_slot"),
  HERO_ID("hero_id"),
  ITEM_0("item_0"),
  ITEM_1("item_1"),
  ITEM_2("item_2"),
  ITEM_3("item_3"),
  ITEM_4("item_4"),
  ITEM_5("item_5"),
  KILLS("kills"),
  DEATHS("deaths"),
  ASSISTS("assists"),
  LEAVER_STATUS("leaver_status"),
  //  GOLD,
  LAST_HITS("last_hits"),
  DENIES("denies"),
  GOLD_PER_MIN("gold_per_min"),
  XP_PER_MIN("xp_per_min"),
  //GOLD_SPENT,
  HERO_DAMAGE("hero_damage"),
  TOWER_DAMAGE("tower_damage"),
  HERO_HEALING("hero_healing"),
  LEVEL("level"),
  //ADDITIONAL_UNITS,
  STUNS("stuns"),
  //MAX_HERO_HIT,
  //TIMES,
  //GOLD_T,
  //LH_T,
  //XP_T,
  //SEN_LOG,
  //PURCHASE_LOG,
  //KILLS_LOG,
  //BUYBACK_LOG,
  //LANE_POS,
  OBS("obs"),
  SEN("sen"),
  //ACTIONS,
  PINGS("pings"),
  PURCHASE("purchase"),
  //GOLD_REASONS,
  //XP_REASONS,
  //KILLED,
  ITEM_USES("item_uses"),
  //ABILITY_USES,
  //HERO_HITS,
  //DAMAGE,
  //DAMAGE_TAKEN,
  //DAMAGE_INFLICTOR,
  //RUNES,
  //KILLED_BY,
  KILL_STREAKS("kill_streaks"),
  MULTI_KILLS("multi_kills"),
  //LIFE_STATE,
  //DAMAGE_INFLICTOR_RECEIVED,
  //OBS_PLACED,
  //SEN_PLACED,
  //CREEPS_STACKED,
  //CAMPS_STACKED,
  //RUNE_PICKUPS,
  //OBS_LEFT_LOG,
  //SEN_LEFT_LOG,
  //ABILITY_UPGRADES,
  //PARTY_ID,
  //PERMANENT_BUFFS,
  //BACKPACK_0,
  //BACKPACK_1,
  //BACKPACK_2,
  //RUNES_LOG,
  LANE("lane"),
  LANE_ROLE("lane_role"),
  IS_ROAMING("is_roaming"),
  //FIRSTBLOOD_CLAIMED,
  //TEAMFIGHT_PARTICIPATION,
  //TOWERS_KILLED,
  //ROSHANS_KILLED,
  //OBSERVERS_PLACED,
  PARTY_SIZE("party_size"),
  //ABILITY_TARGETS,
  //DAMAGE_TARGETS,
  //DN_T,
  //CONNECTION_LOG,
  //BACKPACK_3,
  ITEM_NEUTRAL("item_neutral"),
  //NET_WORTH,
  //HERO_VARIANT,
  //NEUTRAL_TOKENS_LOG,
  //NEUTRAL_ITEMS_HISTORY;
  ;

  private final String queryParam;

  private MatchField(final String param) {
    this.queryParam = param;
  }

  public String getQueryParam() {
    return queryParam;
  }
}
